
# $misc/CP/mpv.conf
# (see also  /usr/share/doc/mpv/mpv.conf)
#  symlinked by
#   $MSn/set/3.ps1
#   $OSAB/nodes-set/jo-3-when_myDrA.sh

osd-level=3
volume=50

# $ITccl/CP/mpv-scripts/ ($misc/GRs/cGRs-needed.sh)
#           quack.lua: 2s fade up from -10 after each positional start
#  firequalizer15.lua: Ctrl+e  invokes equalizer
#      visualizer.lua: c  cycles through visualisations

